name: Pizza Planet CI
on:
  pull_request:
    branches:
      - main

jobs:
  CI-PIZA-PLANET-BACKEND:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install requirements
        run: make install-requirements

      - name: Run formatter check
        run: make run-linters

      - name: Run Test
        run: make pytest
